language: ruby
rvm:
  - 2.2

cache:
  directories:
    - vendor

before_script:
  - sudo apt-get install ncftp

script:
  - bundle exec jekyll build

after_success:
  - "ncftpput -R -v -u "$FTP_USER" -p "$FTP_PASSWORD" $FTP_HOST $FTP_PATH _site/*"

branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - FTP_HOST=qxu1146520061.my3w.com
  - FTP_PATH=/htdocs/hi-ruby.com

sudo: required # route your build to the container-based infrastructure for a faster build