# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hi-Ruby中文站
email: support@hi-ruby.com
description: 
  Hi-Ruby中文站
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hi-ruby.com" # the base hostname & protocol for your site
twitter_username: bluebu2010
github_username:  bluebu
timezone: Asia/Shanghai
encoding: utf-8

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/pages/:num"

kramdown:
  input: GFM 
  syntax_highlighter: rouge

gems: 
  - jekyll-paginate

sitemap:
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# # collections
# collections:
#   - categories


defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      excerpt_separator: <!--more-->
  # -
  #   scope:
  #     path: "categories" # an empty string here means all files in the project
  #     type: "categories" # previously `post` in Jekyll 2.2.
  #   values:
  #     layout: "default"
